version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/project
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres